name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  ci:
    name: Lint code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v6

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Install dependencies 📦
        run: |
          uv pip install pytest --group dev

      - name: Lint code 🧹
        run: |
          uv run --no-project ruff check .

      - name: Test code 🧪
        run: |
          if [ -d "tests" ]; then
            SWANHUB_ENV=dev pytest tests/
          fi
